### ISSUE TITLE
Default package request

### ISSUE THREAD

**Issue by meshya** [parchlinux/Parch-iso-gnome#11]
Hello ✋🏼  
May U add  gnome-terminal-transparency by default ?

**Comment by behdanisohrab** [comment]
@meshya Gnome terminal is removed in latest release

**Comment by meshya** [comment]
![Screenshot from 2024-07-16 16-20-34](https://github.com/user-attachments/assets/12db9c94-cede-4731-baf3-0228598875d1)

**Comment by meshya** [comment]
Ok, thanks 😆
